version: '3'

networks:
  etcd_net:

volumes:
    etcd_vol0:

services:
  etcd0:
    container_name: etcd0
    image: endlessday3/etcd:v3.3
    ports:
      - 2379:2379
    environment:
      - TZ=CST-8
    command: >-
      /usr/local/bin/etcd
      -name etcd0
      -data-dir /etcd-data
      -advertise-client-urls http://etcd0:2379
      -listen-client-urls http://0.0.0.0:2379
      -initial-advertise-peer-urls http://etcd0:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token single-etcd
      -initial-cluster etcd0=http://etcd0:2380
      -initial-cluster-state new
    volumes:
      - etcd_vol0:/etcd-data
    networks:
      - etcd_net

  etcd_browser:
    container_name: etcd_browser
    image: buddho/etcd-browser
    ports:
      - 8000:8000
    environment:
      - ETCD_HOST=etcd0
      - ETCD_PORT=2379
      - SERVER_PORT=8000
    networks:
      - etcd_net